/**
 * REDCap contract tests — amarre-specific metadata.
 *
 * Validates that the amarre data dictionary (data-dictionaries/127-amarre-v1.json)
 * imported into a freshly provisioned project surfaces the fields and
 * instruments that the amarre app relies on.
 *
 * Test prerequisites :
 *   - REDCap docker up (`pnpm docker:up && pnpm docker:install`)
 *   - Amarre project provisioned via `pnpm test:setup`
 *     (REDCAP_TOKEN_PROJECT_AMARRE in docker/config/.env.test)
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

interface AmarreFixture {
  title: string;
  token: string;
  recordCount: number;
}

interface FixturesConfig {
  apiUrl: string;
  amarre: AmarreFixture;
}

const FIXTURES_PATH = join(import.meta.dirname, '../fixtures/projects.json');

let amarre: AmarreFixture;
let apiUrl: string;

async function postApi(
  params: Record<string, string>
): Promise<{ status: number; data: unknown; text: string }> {
  const body = new URLSearchParams(params);
  const r = await fetch(apiUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: body.toString(),
  });
  const text = await r.text();
  let data: unknown;
  try {
    data = JSON.parse(text);
  } catch {
    data = text;
  }
  return { status: r.status, data, text };
}

describe('Amarre — metadata contract', () => {
  beforeAll(() => {
    if (!existsSync(FIXTURES_PATH)) {
      throw new Error('Fixtures not found. Run: pnpm test:setup');
    }
    const fixtures = JSON.parse(readFileSync(FIXTURES_PATH, 'utf-8')) as FixturesConfig;
    apiUrl = fixtures.apiUrl;
    amarre = fixtures.amarre;
    if (!amarre?.token) {
      throw new Error('Amarre fixture missing — re-run pnpm test:setup');
    }
  });

  it('GET project info returns title="amarre" and in_production=0', async () => {
    const { status, data } = await postApi({
      token: amarre.token,
      content: 'project',
      format: 'json',
    });
    expect(status).toBe(200);
    const project = data as { project_title?: string; in_production?: number };
    expect(project.project_title).toBe('amarre');
    expect(project.in_production).toBe(0);
  });

  it('GET metadata returns 113 valid fields (5 placeholders dropped at import)', async () => {
    const { status, data } = await postApi({
      token: amarre.token,
      content: 'metadata',
      format: 'json',
    });
    expect(status).toBe(200);
    expect(Array.isArray(data)).toBe(true);
    const fields = data as Array<Record<string, unknown>>;
    expect(fields).toHaveLength(113);
  });

  it('exposes the field names the amarre app reads (record_id, email, userid, …)', async () => {
    const { data } = await postApi({
      token: amarre.token,
      content: 'metadata',
      format: 'json',
    });
    const names = new Set((data as Array<{ field_name: string }>).map((f) => f.field_name));
    // Cf. apps/amarre/src/lib/server/services/surveys.ts (newRequest payload)
    // and apps/amarre/src/lib/types/api/surveys.ts (SurveyRequestItem).
    // NB: `*_complete` fields are auto-generated by REDCap per form and
    // are NOT exposed by GET metadata — they appear only on record exports.
    for (const required of [
      'record_id',
      'email',
      'userid',
      'created_at',
      'demandeur_statut',
      'mobilite_type',
      'invitation_type',
      'invite_nom',
      'avis_composante_position',
      'avis_laboratoire_position',
      'avis_encadrant_position',
    ]) {
      expect(names.has(required), `missing field "${required}"`).toBe(true);
    }
  });

  it('imports branching_logic on conditional fields (e.g. demandeur_composante)', async () => {
    const { data } = await postApi({
      token: amarre.token,
      content: 'metadata',
      format: 'json',
    });
    const fields = data as Array<{ field_name: string; branching_logic?: string }>;
    const composante = fields.find((f) => f.field_name === 'demandeur_composante');
    expect(composante).toBeDefined();
    expect(composante?.branching_logic).toMatch(/\[demandeur_statut\]/);
  });

  it('exposes the 11 amarre instruments (forms)', async () => {
    const { status, data } = await postApi({
      token: amarre.token,
      content: 'instrument',
      format: 'json',
    });
    expect(status).toBe(200);
    const instruments = data as Array<{ instrument_name: string }>;
    // Cf. data-dictionaries/127-amarre-v1.json `.instruments[]`.
    const expected = [
      'contact',
      'form',
      'demandeur_composante',
      'labo',
      'encadrant',
      'validation_finale',
      'admin',
      'dossier_reviewer',
      'reviewer_1',
      'reviewer_2',
      'reviewer_3',
    ];
    const names = instruments.map((i) => i.instrument_name);
    for (const e of expected) {
      expect(names, `missing instrument "${e}"`).toContain(e);
    }
  });

  it('rejects record import for redacted/invalid field names', async () => {
    // Sanity: confirms our import-time filter (cf. redcap-admin.ts
    // VALID_FIELD_NAME) is consistent with what REDCap actually accepts
    // on the record/import side.
    const { status, data } = await postApi({
      token: amarre.token,
      content: 'record',
      action: 'import',
      format: 'json',
      type: 'flat',
      data: JSON.stringify([
        {
          record_id: 'rejected-001',
          'alignement_[REDACTED]': 'should-fail',
        },
      ]),
    });
    expect(status).toBe(400);
    const body = data as { error?: string };
    expect(body.error).toMatch(/not found in the project as real data fields/i);
  });
});
