export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'amarre',
        'amarre-sandbox',
        'baas',
        'auth',
        'biblio-cli',
        'ci',
        'config',
        'crf',
        'crf-cli',
        'deps',
        'docs',
        'ecrin',
        'errors',
        'citation',
        'citation-cli',
        'citation-fetch',
        'citation-types',
        'citation-validate',
        'fetch-one-api-page',
        'find-an-expert',
        'infra',
        'net',
        'net-cli',
        'crf-client',
        'crf-core',
        'crf-dashboard',
        'crf-logs',
        'crf-openapi',
        'crf-sandbox',
        'crf-stats',
        'researcher-profiles',
        'validators',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
  },
};
