packages:
  - packages/*
  - apps/*
  - services/*
  - tools/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - lefthook
  - msgpackr-extract
  - protobufjs
  - unrs-resolver
  - vue-demi
