packages:
  - apps/*
  - cli/*
  - config/*
  - packages/*
  - sandbox/*
  - services/*

onlyBuiltDependencies:
  - '@duckdb/node-api'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - core-js
  - esbuild
  - lefthook
  - msgpackr-extract
  - protobufjs
  - sharp
  - tesseract.js
  - unrs-resolver
  - vue-demi
