// Reachability probes for the level-5 stack. Each probe is bounded so
// the test boot doesn't hang when a service is down — a fast skip is
// better DX than a 60s vitest hookTimeout.
//
// We probe Mailpit + Appwrite admin. amarre dev itself is handled by
// Playwright's `webServer` block in `playwright.config.ts` (it spawns
// the dev server if not already up). REDCap isn't probed because
// `signupWithEmail` falls back to `ID.unique()` when REDCap errors —
// the full smoke doesn't strictly need REDCap up.

import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const MAILPIT_URL = process.env["MAILPIT_URL"] ?? "http://localhost:8025";
const APPWRITE_ENDPOINT =
  process.env["PUBLIC_APPWRITE_ENDPOINT"] ?? "http://localhost:8090/v1";

const probe = async (url: string, init?: RequestInit): Promise<boolean> => {
  try {
    const response = await fetch(url, {
      ...init,
      signal: AbortSignal.timeout(2_000),
    });
    return response.ok;
  } catch {
    return false;
  }
};

const isMailpitReachable = (): Promise<boolean> =>
  probe(`${MAILPIT_URL}/api/v1/messages?limit=1`);

/**
 * Reads `apps/amarre/.env.local` (gitignored, regenerated by
 * `pnpm -F @univ-lehavre/atlas-amarre-sandbox bootstrap`) to find the
 * Appwrite project + API key. Returns `{}` when the file or values
 * aren't available — then the probe naturally fails and the suite skips.
 */
const readAmarreEnv = (): Record<string, string> => {
  const path = resolve(
    new URL(".", import.meta.url).pathname,
    "../../../../../apps/amarre/.env.local",
  );
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(path, "utf-8").split(/\r?\n/)) {
    const match = line.match(/^([A-Z_]+)="?([^"\n]+)"?$/);
    if (match) out[match[1]!] = match[2]!;
  }
  return out;
};

const isAppwriteReachable = async (): Promise<boolean> => {
  const env = readAmarreEnv();
  const project = env["PUBLIC_APPWRITE_PROJECT"];
  const apiKey = env["APPWRITE_KEY"];
  if (!project || !apiKey) return false;
  return probe(`${APPWRITE_ENDPOINT}/users?limit=1`, {
    headers: {
      "X-Appwrite-Project": project,
      "X-Appwrite-Key": apiKey,
    },
  });
};

export const isStackReachable = async (): Promise<boolean> => {
  const [mailpit, appwrite] = await Promise.all([
    isMailpitReachable(),
    isAppwriteReachable(),
  ]);
  return mailpit && appwrite;
};
