#!/usr/bin/env bash
# Writes a ready-to-use `.env.local` for the sillage SvelteKit app
# pointing at the local sandbox services.

set -euo pipefail

cd "$(dirname "$0")/.."

# shellcheck disable=SC1091
source .env

target="../../apps/sillage/.env.local"

cat > "$target" <<EOF
# Generated by sandbox/sillage-sandbox/scripts/write-sillage-env.sh
# Reflects the running local sandbox (BaaS + CRF). Re-run after
# rotating tokens or rebuilding the sandbox.

ALLOWED_DOMAINS_REGEXP="${ALLOWED_DOMAINS_REGEXP:-@(example\\.org|univ-lehavre\\.fr)}"
PUBLIC_LOGIN_URL="${PUBLIC_LOGIN_URL:-http://localhost:5173}"

# BaaS (Appwrite self-hosted)
PUBLIC_APPWRITE_ENDPOINT="${PUBLIC_APPWRITE_ENDPOINT}"
PUBLIC_APPWRITE_PROJECT="${PUBLIC_APPWRITE_PROJECT}"
APPWRITE_KEY="${APPWRITE_KEY}"

# CRF (REDCap)
PUBLIC_REDCAP_URL="${PUBLIC_CRF_URL}"
REDCAP_API_TOKEN="${CRF_API_TOKEN}"
EOF

echo "OK — wrote $target"
